/*!
 * @author Satyajit319 <satyajit319@gmail.com>
 * date 27/03/2022
 */
let firstMaleName = ['Hari', 'sam', 'Mukund', 'Nabaghan', 'Abhishek', 'Suresh', 'Santunu', 'Akashya', 'Haribol',
  'Madhab', 'Balkrushna', 'Aarav', 'Vihaan', 'Vivaan', 'Ananya', 'Diya', 'Advik', 'Kabir', 'Anaya',
  'Aarav', 'Vivaan', 'Aditya', 'Vivaan', 'Vihaan', 'Arjun', 'Vivaan', 'Reyansh', 'Mohammed', 'Sai',
  'Arnav', 'Aayan', 'Krishna', 'Ishaan', 'Shaurya', 'Atharva', 'Advik', 'Pranav', 'Advaith', 'Aaryan',
  'Dhruv', 'Kabir', 'Ritvik', 'Aarush', 'Kian', 'Darsh', 'Veer', 'Aadil', 'Aakash', 'Aarif',
  'Aashu', 'Aatif', 'Aayush', 'Abdul', 'Abdullah', 'Abhash', 'Abhimanyu', 'Abhinav', 'Abhishek', 'Abrar',
  'Adi', 'Aditya', 'Aftab', 'Agyapad', 'Ahsan', 'Ajay', 'Ajeet', 'Ajit', 'Ajman', 'Akash',
  'Akbar', 'Akhilesh', 'Akhtar', 'Akram', 'Akshay', 'Akshpaat', 'Altaf', 'Aman', 'Amar', 'Amarjeet',
  'Ameen', 'Amil', 'Amit', 'Anil', 'Anjali', 'Ankit', 'Ankur', 'Ansh', 'Anshu', 'Anshul',
  'Ansu', 'Anuj', 'Anup', 'Anurag', 'Anwari', 'Aoosaf', 'Arif', 'Arman', 'Arsad',
  'Arsh', 'Arun', 'Arvind', 'Aryan', 'Ashish', 'Ashok', 'Ashu', 'Ashutosh', 'Asif', 'Atul',
  'Avinash', 'Ayan', 'Azam', 'Bablu', 'Babu', 'Babulal', 'Baksi', 'Balbir', 'Balram', 'Balwant',
  'Banarsi', 'Bandu', 'Bangali', 'Banwari', 'Barkat', 'Begraj', 'Bhagwans', 'Bhajanlal', 'Bhanu',
  'Bharma', 'Bhupender', 'Bhupesh', 'Bijender', 'Bijendra', 'Bikki', 'Birender', 'Birij', 'Birjesh', 'Bishan',
  'Bittu', 'Bobi', 'Boby', 'Bram', 'Brijmohan', 'Chandan', 'Chander', 'Chanderpal', 'Chandra', 'Chandrram',
  'Chatan', 'Chatar', 'Chaterpal', 'Cheddi', 'Chetan', 'Chetanram', 'Chirag', 'Chitrangans', 'Chran', 'Daler',
  'Daniel', 'Danish', 'Daya', 'Deep', 'Deepak', 'Deepchand', 'Deepender', 'Deewan', 'Desh',
  'Deshraj', 'Deva', 'Devender', 'Devinder', 'Devraj', 'Dhalchand', 'Dhanna', 'Dharam', 'Dharmandra', 'Dharmender',
  'Dharmvir', 'Dheeraj', 'Dhramender', 'Dhrmveer', 'Dilip', 'Dinesh', 'Divansh', 'Divyansh', 'Dular', 'Durganand',
  'Faijal', 'Farid', 'Farmaan', 'Firoj', 'Fulmiya', 'Ganesh', 'Gaurav', 'Gauri', 'Gautam', 'Ghan',
  'Ghanshyam', 'Giri', 'Girish', 'Gopi', 'Gorav', 'Gourav', 'Gulfam', 'Gulreg', 'Gulshan', 'Gyanendra',
  'Haider', 'Hansraj', 'Harak', 'Hararat', 'Harendra', 'Hari', 'Harish', 'Harison', 'Harkesh', 'Harpal',
  'Harsh', 'Harshal', 'Harvinder', 'Hazrat', 'Hemant', 'Himanshu', 'Hosiyarilal', 'Hrithik', 'Imran', 'Inder',
  'Inderjeet', 'Irshad', 'Ishan', 'Ishant', 'Ishwar', 'Islam', 'Jabbar', 'Jabir', 'Jagmal', 'Jahagir',
  'Jahid', 'Jaiprakash', 'Jasbir', 'Jasveer', 'Jatin', 'Javed', 'Jeeshan', 'Jeetu', 'Jeeya', 'Jitender',
  'Jitendera', 'Jitendra', 'Kabul', 'Kaif', 'Kalu', 'Kamruddin', 'Kanhaiya', 'Kapil',
  'Karan', 'Kavilash', 'Keshave', 'Khemraj', 'Khursheed', 'Kiran', 'Kishan', 'Kripal', 'Krishan', 'Krishana',
  'Kuldeep', 'Kumar', 'Kumari', 'Kunal', 'Kundan', 'Kushal', 'Laksh', 'Lal', 'Lalan', 'Lalaram',
  'Lalit', 'Lamani', 'Lave', 'Lawrence', 'Laxman', 'Lekhraj', 'Leo', 'Loknath', 'Lokesh',
  'Madan', 'Mahaveer', 'Mahender', 'Mahendra', 'Mahesh', 'Mahipal', 'Mamchand', 'Mamta', 'Man', 'Manful',
  'Manish', 'Manjeet', 'Manjiv', 'Mannu', 'Manoj', 'Manpreet', 'Mithlesh', 'Mobin', 'Mohan', 'Mohit',
  'Moni', 'Monu', 'Mukeemuddin', 'Mukesh', 'Muneer', 'Munesh', 'Nadeem', 'Nandkishore', 'Nandmeena', 'Nandu',
  'Nanhe', 'Narayan', 'Narender', 'Naresh', 'Naseem', 'Nashim', 'Neeraj', 'Nikhil', 'Nitin', 'Noorhasan',
  'Omprakash', 'Pancu', 'Pankaj', 'Paras', 'Pardeep', 'Parmod', 'Parteek', 'Partik', 'Pavan', 'Pawan',
  'Phooleshwar', 'Pintu', 'Piyush', 'Pooja', 'Prabhjeet', 'Pradeep', 'Prahlad', 'Pramod', 'Prasant', 'Praveen',
  'Prem', 'Prhalad', 'Prince', 'Punarjyoti', 'Punit', 'Pushkar', 'Puspak', 'Rada', 'Radha', 'Radhey',
  'Raghubir', 'Raghunandan', 'Raghuvir', 'Rahish', 'Rahul', 'Raj', 'Raja', 'Rajan', 'Rajaram', 'Rajeev',
  'Rajendar', 'Rajender', 'Rajesh', 'Rajiv', 'Rajkumar', 'Rajneesh', 'Rajni', 'Raju', 'Rajveer', 'Rakesh',
  'Ram', 'Ramchander', 'Ramesh', 'Ramhetu', 'Ramkishan', 'Ramprasad', 'Ramtek', 'Randhir', 'Ranjeet', 'Ranjit',
  'Raseel', 'Ratiman', 'Ravi', 'Ravikant', 'Ravinder', 'Ravindra', 'Raviraj', 'Ridhakaran', 'Rihan', 'Rinki',
  'Rinku', 'Rishi', 'Riyaz', 'Robin', 'Rohit', 'Ronak', 'Roshan', 'Rupender', 'Rupesh', 'Sachin',
  'Saddam', 'Sahil', 'Sahrukh', 'Sajjan', 'Salim', 'Salin', 'Salmaan', 'Same', 'Sameem', 'Sameer',
  'Samsuddin', 'Sandeep', 'Sanjay', 'Sanjeev', 'Sanjiv', 'Sanni', 'Sanny', 'Santosh', 'Sartaj', 'Sarvan',
  'Satbar', 'Satender', 'Satish', 'Satpal', 'Satyam', 'Satyvrat', 'Saurabh', 'Sehzad', 'Shabuddin', 'Shagufta',
  'Shail', 'Shailesh', 'Shakil', 'Shakti', 'Shambhu', 'Shamim', 'Shankar', 'Sharukh', 'Shashank', 'Shashikant',
  'Shaukat', 'Shayam', 'Shayamveer', 'Shibu', 'Shisupal', 'Shiv', 'Shiva', 'Shivam', 'Shivyalam', 'Shobharam',
  'Shripal', 'Shubham', 'Shyam', 'Shyamlal', 'Shyamveer', 'Sidharath', 'Sivam', 'Somnath', 'Sonu',
  'Subhakar', 'Subhas', 'Subhash', 'Sudhansu', 'Sudhir', 'Suhail', 'Sujeet'
];
let title = ["Sahu", "Behera", "Nayak", "Das", "Pradhan", "Naik", "Majhi", "Jena", "Malik",
  "Swain", "Patra", "Barik", "Mohanty", "Raut", "Bhoi", "Panda", "Sahoo", "Sethy", "Dei",
  "Biswal", "Singh", "Parida", "Munda", "Mahanta", "Mahapatra", "Samal", "Mishra", "Maharana",
  "Rana", "Dash", "Bag", "Dehuri", "Padhan", "Meher", "Gaud", "Pradhana", "Bibi", "Muduli", "Harijan",
  "Shabar", "Sethi", "Jani", "Nag", "Mandal", "Murmu", "Patel", "Rout", "Mallick", "Gauda", "Bhue",
  "Kisan", "Nahak", "Giri", "Pattnayak", "Panigrahi", "Senapati", "Padhi", "Khan", "Bhatara", "Bariha",
  "Dalei", "Bewa", "Lenka", "Bhatra", "Bhuyan", "Mahakud", "Dalai", "Oram", "Ganda", "Suna", "Ray", "Tudu",
  "Gouda", "Pujari", "Tripathi", "Simha", "Ojha", "Kar", "Kumbhar", "Nath", "Nanda", "Sa", "Rath", "Seth",
  "Mohanta", "Dhal", "Mahananda", "Mahalik", "Marndi", "Soren", "Palei", "Baral", "Digal", "Hemrum",
  "Prushti", "Tandi", "Pati", "Bagha", "Dharua", "Khatua", "Bindhani", "Raul", "Pal", "Bagartti", "Kahanra",
  "Putel", "Bisoyi", "Sabar", "Kandi", "Mohapatra", "Shatapathi", "Dakua", "Samantaray", "Khuntia", "Mallik",
  "Santa", "Mirdha", "Khara", "Acharya", "Bisoi", "Begum", "Dip", "Mali", "Pani", "Rao", "Sing", "Gochhayat",
  "Guru", "Agrawal", "Hansdah", "Bal", "Chowdhury", "Khatun", "Hembram", "Pande", "Bisi", "Chhatria", "Sharma",
  "Debi", "Khadia", "Hati", "Dora", "Rautray", "Ghadei", "Mahakur", "Kujur", "Ekka", "Lakra", "Podh", "Mukhi",
  "Khil", "Kumar", "Hantal", "Tarai", "Dehury", "Gahir", "Rait", "Dey", "Saren", "Khamari", "Pattnaik", "Pangi",
  "Ho", "Jal", "Banachhor", "Gamanga", "Alli", "Hota", "Sunani", "Hansa", "Pallai", "Sutar", "Sahani", "Naek",
  "Badatya", "Saha", "Khilar", "Dalabehera", "Dandasena", "Paik", "Pujhari", "Pradhani", "Redi", "Pattanayak",
  "Purtti", "Gond", "Nial", "Bhol", "Mahanti", "Subudhi", "Shadangi", "Biswas", "Madakami", "Kisku", "Paraja",
  "Gadanayak", "Kuanra", "Tripathy", "Barla", "Chanda", "Ghosh", "Bhanja", "Barad", "Rohidas", "Thakur", "Mangaraj",
  "Gadaba", "Chalan", "Datta", "Marandi", "Kalo", "Gupta", "Hansda", "Goud", "Mahakul", "Jhankar", "Ghadai",
  "Beura", "Minz", "Juanga", "Bhumia", "Paikaray", "Sarakar", "Prusty", "Sasamal", "Lohar", "Minja", "Misra",
  "Puhan", "Tanti", "Bagh", "Satanami", "Amanatya", "Thapa", "Lakada", "Behura", "Kadraka", "Budek", "Deo",
  "Kamar", "Moharana", "Kishan", "Dhurua", "Lugun", "Samanta", "Sandh", "Mahanandia", "Kanhar", "Gopal",
  "Beshra", "Badaik", "Luha", "Prasad", "Tirkey", "Tirki", "Mundari", "Bibhar", "Chandan", "Padiami",
  "Bhutia", "Sabat", "Bastia", "Bhoe", "Jhodia", "Raita", "Jagat", "Malla", "Chhatar", "Mahankud", "Baske", "Kata",
  "Badhei", "Danasana", "Mahali", "Satapathy", "Kaanra", "Madi", "Toppo", "Choudhury", "Kharsel", "Bej", "Raj",
  "Durga", "Nandi", "Kanda", "Sisa", "Deheri", "Karmi", "Sen", "Maiti", "Hikaka", "Bishoyi", "Karan", "Purohit",
  "Tappo", "Samad", "Tiria", "Mahar", "Shandh", "Dandapat", "Dalapati", "Pattanaik", "Rama", "Sagar", "Danga",
  "Pingua", "Bhatta", "Kerketta", "Muni", "Kalar", "Mahanty", "Palai", "Debata", "Martha", "Devi", "Tarei",
  "Begam", "Set", "Adhikari", "Agrawalla", "Mantri", "Karnna", "Hial", "Bhati", "Reddy", "Mandangi", "Bhukta",
  "Dhir", "Chhura", "Bidika", "Dungdung", "Parija", "Kabasi", "Kabi", "Mahammad", "Sai", "Tete", "Chatar",
  "Mahala", "Dungadunga", "Durua", "Kumura", "Kulu", "Badi", "Gagarai", "Baliyarasinh", "Hasada", "Mahana",
  "Karua", "Penthei", "Jain", "Mahakhud", "Khatei", "Parichha", "Haladar", "Bemal", "Birua", "Kerketa",
  "Sarangi", "Disari", "Samarath", "Punji", "Bachha", "Lima", "Bhumij", "Huika", "Roul", "Gadatia", "Amat",
  "Takri", "Bishi", "Paridaa", "Keraketa", "Saura", "Patro", "Tandia", "Samantara", "Thela", "Sial", "Polei",
  "Surin", "Si", "Padhiari", "Polai", "Pod", "Jayapuria", "Bai", "Pasayat", "Behuria", "Harapal", "Bhakta",
  "Pramanik", "Tadingi", "Bera", "Kamila", "Dwibedi", "Khanda", "Karji", "Purty", "Achari", "Parmanik", "Haripal",
  "Kandulana", "Kalet", "Chinda", "Harichandan", "Jagadala", "Bhainsa", "Prusti", "Bihari", "Patnaik", "Tapno", "Golari",
  "Sundaray", "Manahira", "Yadab", "Praharaj", "Jali", "Chhotaray", "Kundu", "Bhokta", "Jojo", "Kharasel", "Kumari",
  "Ghibhela", "Pandit", "Ranasingh", "Mistri", "Gochhaet", "Alam", "Mahato", "Matari", "Jana", "Sinku", "Brahma",
  "Gardia", "Bage", "Bharati", "Taria", "Pahan", "Hansadah", "Bano", "Mahunta", "Padhy", "Randhari", "Routray", "Amanta",
  "Deep", "Khandei", "Kandagari", "Kathar", "Guntha", "Ketaki", "Lahajal", "Nisa", "Miniaka", "Parabhue", "Minyaka",
  "Kunda", "Khandual", "Kindo", "Hembrum", "Palaka", "Kahanr", "Chandi", "Halaba", "Krisani", "Tapo", "Puta", "Buda",
  "Bada", "Sagaria", "Chhatoi", "Gudia", "Baskey", "Negi", "Thanapati", "Sin", "Beg", "Lakshmi", "Saraph", "Gadatya",
  "Sika", "Sarddar", "Luhura", "Patamajhi", "Panaka", "Madhei", "Bariki", "Mahalinga", "Soreng", "Babu", "Saunta",
  "Raju", "Gochhi", "Bishoi", "Choudhuri", "Dhangadamajhi", "Basantia", "Rajahansa", "Dibya", "Sodi", "Shrichandan",
  "Samantaraya", "Tanty", "Champia", "Bhaisal", "Bentakar", "Manna", "Kirsani", "Kudei", "Badajena", "Kalata", "Banara",
  "Parua", "Himirika", "Khemundu", "Danta", "Gantayat", "Josi", "Karuan", "Satapathi", "Sidar", "Kuanr", "Shankhua",
  "Dutta", "Kullu", "Eka", "Luhar", "Bud", "Khura", "Baghar", "Meleka", "Khosala", "Muli", "Kuladip", "Gahan", "Apat",
  "Pandey", "Ram", "Adabar", "Pothal", "Bharasagar", "Dikshit", "Sarenga", "Galari", "Sardar", "Gop", "Raika", "Ganta",
  "Kaibartta", "Kaudi", "Deuri", "Bagar", "Banua", "Bhadra", "Kanta", "Keut", "Shadhangi", "Jadab", "Ksheti", "Bandichhor",
  "Balabantaray", "Tiwari", "Mahat", "Sathua", "Pratihari", "Lohara", "Bardhan", "Xalxo", "Praska", "Bairagi", "Dila",
  "Husen", "Saraka", "Kaur", "Dhibar", "Dixit", "Mandinga", "Mandingi", "Gamango", "Saradar", "Paharia", "Hernna",
  "Tigga", "Bar", "Pagal", "Dhar", "Mandi", "Neti", "Sau", "Padhihari", "Bala", "Patri", "Khalakho", "Dhrua", "Barua",
  "Pruseth", "Badarait", "Yadav", "Bhujabal", "Selama", "Mohakud", "Manika", "Yena", "Pidikaka", "Sukla", "Bagarti", "Chakra",
  "Hosen", "Banka", "Kalasae", "Jued", "Uddin", "Budhia", "Khatoi", "Raya", "Madkami", "Debanath", "Agarwal", "Topno", "Pandab",
  "Hans", "Shandha", "Barge", "Upadhyay", "Kabat", "Baidya", "Parabhoe", "Sith", "Jha", "Benia", "Badara", "Sinha",
  "Sihna", "Pasaet", "Parabhoi", "Champati", "Laguri", "Gemel", "Bhainsal", "Chhanda", "Makar", "Xess", "Adha", "Besra",
  "Chhuria", "Kalandi", "Parwin", "Dandia", "Manasinh", "Kanungoo", "Burudi", "Bahadur", "Sarap", "Santara", "Bagal",
  "Madhi", "Garada", "Ansari", "Nachika", "Khakha", "Garadia", "Mitra", "Sabitri", "Bari", "Chakrabarty", "Dangua",
  "Kandulna", "Dwari", "Bir", "Dhada", "Duria", "Bahidar", "Parbati", "Rajak", "Chowhan", "Kheti", "Tunga", "Karakaria",
  "Kido", "Khila", "Paital", "Pahi", "Ghibela", "Burma", "Khatoon", "Raheman", "Sundara", "Penthoi", "Mahal", "Sandha",
  "Marei", "Rauta", "Pattayat", "Karjee", "Muna", "Juadi", "Pidika", "Majumdar", "Jamuda", "Kulesika", "Pinga", "Jati",
  "Panigrahy", "Patika", "Sendh", "Rautaraya", "Mahabhoi", "Kampa", "Marnni", "Dalua", "Parween", "Lahar", "Deogam",
  "Ranabida", "Karmakar", "Sagria", "Badra", "Besan", "Soni", "Ghasi", "Ali", "Urma", "Singha", "Khosla", "Bhosagar",
  "Saraswati", "Karna", "Khes", "Mugri", "Ranajit", "Jethi", "Agasti", "Shatapathy", "Soy", "Aehmad", "Bara", "Bishayi", "Bishai", "Goswami",
  "Mashra", "Mahankuda", "Parimanik", "Karali", "Pandi", "Bhengra", "Beriha", "Rautaray", "Dal", "Kanungo", "Puala", "Bhagat", "Perei",
  "Baliarasinh", "Pan", "Thatoi", "Urlaka", "Baa", "Karyi", "Dhali", "Baitharu", "Samantasinhar", "Khanam", "Muthamajhi", "Bandichhod",
  "Nathasharma", "Mahamad", "Bahalia", "Hansada", "Jayasinh", "Jerai", "Roy", "Shagadia", "Muria", "Gain", "Barman", "Kalia", "Pushti",
  "Badamundi", "Kusulia", "Lahara", "Sarkar", "Biswakarma", "Baliarasin", "Kandh", "Sah", "Chaudhuri", "Kiro", "Misal", "Peda",
  "Sirika", "Jagadeb", "Guin", "Sidu", "Behara", "Garia", "Sana", "Modi", "Bilunga", "Satpathy", "Suar", "Adajuad", "Sikaka", "Suren", "Matia",
];
let emlDomain = ['gmail.com', 'yahoo.com', 'hotmail.com', 'rediffmail.com', 'mns.com', 'github.com', 'bandu.com', 'baidu.com', 'aol.com', 'comcast.net'];
let upiDomain = ['@BARODAMPAY', '@rbl', '@idbi', '@upi', '@aubank', '@axisbank', '@bandhan', '@dlb', '@indus', '@kbl', '@federal', '@sbi', '@uco',
  '@yesbank', '@citi', '@citigold', '@dlb', '@dbs', '@freecharge', '@okhdfcbank', '@okaxis', '@oksbi', '@okicici', '@hsbc',
  '@idbi', '@icici', '@indianbank', '@allbank', '@kotak', '@ikwik', '@paytm', '@ybl', '@axl', '@ibl', '@sib']
let gender = ['Male', 'Female', 'TransGender'];
let hairColor = ['Black', 'Brown', 'Red', 'Blond'];
let skinColor = ['Ivory', 'Beige', 'Alabaster', 'Honey', 'Carotenoid', 'Tan', 'Caramel', 'Bronze', 'Mahogany', 'Chestnut', 'Buff', 'Peaches', 'Umber', 'Praline', 'Espresso Brown', 'Porcelain', 'Hickory', 'Mustard', 'Sable', 'Almond', 'Bisque', 'Teak', 'Cacao', 'Pecan', 'Saddle Brown'];
let bloodGroup = ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'];
let eyeColor = ['Brown', 'Blue', 'Hazel', 'Amber', 'Green', 'Gray', 'Red'];
let stateName = ['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'];
let stateDist = {
  'Andhra Pradesh': ['Anantapuram', 'Chittoor', 'East Godavari', 'Guntur', 'YSR Kadapa', 'Krishna', 'Kurnool', 'Prakasam', 'Sri Potti Sriramulu Nellore', 'Srikakulam', 'Visakhapatnam', 'Vizianagaram', 'West Godavari'],
  'Arunachal Pradesh': ['Anjaw', 'Changlang', 'Dibang Valley', 'East Kameng', 'East Siang', 'Kamle', 'Kra Daadi', 'Kurung Kumey', 'Lepa Rada', 'Lohit', 'Longding', 'Lower Dibang Valley', 'Lower Siang', 'Lower Subansiri', 'Namsai', 'Pakke Kessang', 'Papum Pare', 'Shi Yomi', 'Siang', 'Tawang', 'Tirap', 'Upper Siang', 'Upper Subansiri', 'West Kameng', 'West Siang'],
  'Assam': ['Baksa', 'Barpeta', 'Biswanath', 'Bongaigaon', 'Cachar', 'Charaideo', 'Chirang', 'Darrang', 'Dhemaji', 'Dhubri', 'Dibrugarh', 'Dima Hasao', 'Goalpara', 'Golaghat', 'Hailakandi', 'Hojai', 'Jorhat', 'Kamrup', 'Kamrup Metropolitan', 'Karbi Anglong', 'Karimganj', 'Kokrajhar', 'Lakhimpur', 'Majuli', 'Morigaon', 'Nagaon', 'Nalbari', 'Sivasagar', 'South Salmara Mankachar', 'Sonitpur', 'Tinsukia', 'Udalguri', 'West Karbi Anglong'],
  'Bihar': ['Araria', 'Arwal', 'Aurangabad', 'Banka', 'Begusarai', 'Bhagalpur', 'Bhojpur', 'Buxar', 'Darbhanga', 'East Champaran', 'Gaya', 'Gopalganj', 'Jamui', 'Jehanabad', 'Kaimur', 'Katihar', 'Khagaria', 'Kishanganj', 'Lakhisarai', 'Madhepura', 'Madhubani', 'Munger', 'Muzaffarpur', 'Nalanda', 'Nawada', 'Patna', 'Purnia', 'Rohtas', 'Saharsa', 'Samastipur', 'Saran', 'Sheikhpura', 'Sheohar', 'Sitamarhi', 'Siwan', 'Supaul', 'Vaishali', 'West Champaran'],
  'Chhattisgarh': ['Balod', 'Baloda Bazar', 'Balrampur', 'Bastar', 'Bemetara', 'Bijapur', 'Bilaspur', 'Dantewada', 'Dhamtari', 'Durg', 'Gariyaband', 'Janjgir-Champa', 'Jashpur', 'Kabirdham', 'Kanker', 'Kondagaon', 'Korba', 'Korea', 'Mahasamund', 'Mungeli', 'Narayanpur', 'Raigarh', 'Raipur', 'Rajnandgaon', 'Sukma', 'Surajpur', 'Surguja'],
  'Goa': ['North Goa', 'South Goa'],
  'Gujarat': ['Ahmedabad', 'Amreli', 'Anand', 'Aravalli', 'Banaskantha (Palanpur)', 'Bharuch', 'Bhavnagar', 'Botad', 'Chhota Udepur', 'Dahod', 'Dangs (Ahwa)', 'Devbhoomi Dwarka', 'Gandhinagar', 'Gir Somnath', 'Jamnagar', 'Junagadh', 'Kachchh', 'Kheda (Nadiad)', 'Mahisagar', 'Mehsana', 'Morbi', 'Narmada (Rajpipla)', 'Navsari', 'Panchmahal (Godhra)', 'Patan', 'Porbandar', 'Rajkot', 'Sabarkantha (Himmatnagar)', 'Surat', 'Surendranagar', 'Tapi (Vyara)', 'Vadodara', 'Valsad'],
  'Haryana': ['Ambala', 'Bhiwani', 'Charkhi Dadri', 'Faridabad', 'Fatehabad', 'Gurugram (Gurgaon)', 'Hisar', 'Jhajjar', 'Jind', 'Kaithal', 'Karnal', 'Kurukshetra', 'Mahendragarh', 'Nuh', 'Palwal', 'Panchkula', 'Panipat', 'Rewari', 'Rohtak', 'Sirsa', 'Sonipat', 'Yamunanagar'],
  'Himachal Pradesh': ['Bilaspur', 'Chamba', 'Hamirpur', 'Kangra', 'Kinnaur', 'Kullu', 'Lahaul & Spiti', 'Mandi', 'Shimla', 'Sirmaur (Sirmour)', 'Solan', 'Una'],
  'Jharkhand': ['Bokaro', 'Chatra', 'Deoghar', 'Dhanbad', 'Dumka', 'East Singhbhum', 'Garhwa', 'Giridih', 'Godda', 'Gumla', 'Hazaribag', 'Jamtara', 'Khunti', 'Koderma', 'Latehar', 'Lohardaga', 'Pakur', 'Palamu', 'Ramgarh', 'Ranchi', 'Sahibganj', 'Seraikela-Kharsawan', 'Simdega', 'West Singhbhum'],
  'Karnataka': ['Bagalkot', 'Ballari (Bellary)', 'Belagavi (Belgaum)', 'Bengaluru (Bangalore) Rural', 'Bengaluru (Bangalore) Urban', 'Bidar', 'Chamarajanagar', 'Chikballapur', 'Chikkamagaluru (Chikmagalur)', 'Chitradurga', 'Dakshina Kannada', 'Davangere', 'Dharwad', 'Gadag', 'Hassan', 'Haveri', 'Kalaburagi (Gulbarga)', 'Kodagu', 'Kolar', 'Koppal', 'Mandya', 'Mysuru (Mysore)', 'Raichur', 'Ramanagara', 'Shivamogga (Shimoga)', 'Tumakuru (Tumkur)', 'Udupi', 'Uttara Kannada (Karwar)', 'Vijayapura (Bijapur)', 'Yadgir'],
  'Kerala': ['Alappuzha', 'Ernakulam', 'Idukki', 'Kannur', 'Kasaragod', 'Kollam', 'Kottayam', 'Kozhikode', 'Malappuram', 'Palakkad', 'Pathanamthitta', 'Thiruvananthapuram', 'Thrissur', 'Wayanad'],
  'Madhya Pradesh': ['Agar Malwa', 'Alirajpur', 'Anuppur', 'Ashoknagar', 'Balaghat', 'Barwani', 'Betul', 'Bhind', 'Bhopal', 'Burhanpur', 'Chhatarpur', 'Chhindwara', 'Damoh', 'Datia', 'Dewas', 'Dhar', 'Dindori', 'Guna', 'Gwalior', 'Harda', 'Hoshangabad', 'Indore', 'Jabalpur', 'Jhabua', 'Katni', 'Khandwa', 'Khargone', 'Mandla', 'Mandsaur', 'Morena', 'Narsinghpur', 'Neemuch', 'Panna', 'Raisen', 'Rajgarh', 'Ratlam', 'Rewa', 'Sagar', 'Satna', 'Sehore', 'Seoni', 'Shahdol', 'Shajapur', 'Sheopur', 'Shivpuri', 'Sidhi', 'Singrauli', 'Tikamgarh', 'Ujjain', 'Umaria', 'Vidisha'],
  'Maharashtra': ['Ahmednagar', 'Akola', 'Amravati', 'Aurangabad', 'Beed', 'Bhandara', 'Buldhana', 'Chandrapur', 'Dhule', 'Gadchiroli', 'Gondia', 'Hingoli', 'Jalgaon', 'Jalna', 'Kolhapur', 'Latur', 'Mumbai City', 'Mumbai Suburban', 'Nagpur', 'Nanded', 'Nandurbar', 'Nashik', 'Osmanabad', 'Palghar', 'Parbhani', 'Pune', 'Raigad', 'Ratnagiri', 'Sangli', 'Satara', 'Sindhudurg', 'Solapur', 'Thane', 'Wardha', 'Washim', 'Yavatmal'],
  'Manipur': ['Bishnupur', 'Chandel', 'Churachandpur', 'Imphal East', 'Imphal West', 'Jiribam', 'Kakching', 'Kamjong', 'Kangpokpi', 'Noney', 'Pherzawl', 'Senapati', 'Tamenglong', 'Tengnoupal', 'Thoubal', 'Ukhrul'],
  'Meghalaya': ['East Garo Hills', 'East Jaintia Hills', 'East Khasi Hills', 'North Garo Hills', 'Ri Bhoi', 'South Garo Hills', 'South West Garo Hills', 'South West Khasi Hills', 'West Garo Hills', 'West Jaintia Hills', 'West Khasi Hills'],
  'Mizoram': ['Aizawl', 'Champhai', 'Kolasib', 'Lawngtlai', 'Lunglei', 'Mamit', 'Saiha', 'Serchhip'],
  'Nagaland': ['Dimapur', 'Kiphire', 'Kohima', 'Longleng', 'Mokokchung', 'Mon', 'Peren', 'Phek', 'Tuensang', 'Wokha', 'Zunheboto'],
  'Odisha': ['Angul', 'Balangir', 'Balasore', 'Bargarh', 'Bhadrak', 'Boudh', 'Cuttack', 'Deogarh', 'Dhenkanal', 'Gajapati', 'Ganjam', 'Jagatsinghapur', 'Jajpur', 'Jharsuguda', 'Kalahandi', 'Kandhamal', 'Kendrapara', 'Kendujhar (Keonjhar)', 'Khordha', 'Koraput', 'Malkangiri', 'Mayurbhanj', 'Nabarangpur', 'Nayagarh', 'Nuapada', 'Puri', 'Rayagada', 'Sambalpur', 'Sonepur', 'Sundargarh'],
  'Punjab': ['Amritsar', 'Barnala', 'Bathinda', 'Faridkot', 'Fatehgarh Sahib', 'Fazilka', 'Ferozepur', 'Gurdaspur', 'Hoshiarpur', 'Jalandhar', 'Kapurthala', 'Ludhiana', 'Mansa', 'Moga', 'Muktsar', 'Nawanshahr (Shahid Bhagat Singh Nagar)', 'Pathankot', 'Patiala', 'Rupnagar', 'Sahibzada Ajit Singh Nagar (Mohali)', 'Sangrur', 'Tarn Taran'],
  'Rajasthan': ['Ajmer', 'Alwar', 'Banswara', 'Baran', 'Barmer', 'Bharatpur', 'Bhilwara', 'Bikaner', 'Bundi', 'Chittorgarh', 'Churu', 'Dausa', 'Dholpur', 'Dungarpur', 'Hanumangarh', 'Jaipur', 'Jaisalmer', 'Jalore', 'Jhalawar', 'Jhunjhunu', 'Jodhpur', 'Karauli', 'Kota', 'Nagaur', 'Pali', 'Pratapgarh', 'Rajsamand', 'Sawai Madhopur', 'Sikar', 'Sirohi', 'Sri Ganganagar', 'Tonk', 'Udaipur'],
  'Sikkim': ['East Sikkim', 'North Sikkim', 'South Sikkim', 'West Sikkim'],
  'Tamil Nadu': ['Ariyalur', 'Chengalpattu', 'Chennai', 'Coimbatore', 'Cuddalore', 'Dharmapuri', 'Dindigul', 'Erode', 'Kallakurichi', 'Kanchipuram', 'Kanyakumari', 'Karur', 'Krishnagiri', 'Madurai', 'Nagapattinam', 'Namakkal', 'Nilgiris', 'Perambalur', 'Pudukkottai', 'Ramanathapuram', 'Ranipet', 'Salem', 'Sivaganga', 'Tenkasi', 'Thanjavur', 'Theni', 'Thoothukudi (Tuticorin)', 'Tiruchirappalli', 'Tirunelveli', 'Tirupathur', 'Tiruppur', 'Tiruvallur', 'Tiruvannamalai', 'Tiruvarur', 'Vellore', 'Viluppuram', 'Virudhunagar'],
  'Telangana': ['Adilabad', 'Bhadradri Kothagudem', 'Hyderabad', 'Jagtial', 'Jangaon', 'Jayashankar Bhoopalpally', 'Jogulamba Gadwal', 'Kamareddy', 'Karimnagar', 'Khammam', 'Komaram Bheem Asifabad', 'Mahabubabad', 'Mahabubnagar', 'Mancherial', 'Medak', 'Medchal', 'Nagarkurnool', 'Nalgonda', 'Nirmal', 'Nizamabad', 'Peddapalli', 'Rajanna Sircilla', 'Rangareddy', 'Sangareddy', 'Siddipet', 'Suryapet', 'Vikarabad', 'Wanaparthy', 'Warangal (Rural)', 'Warangal (Urban)', 'Yadadri Bhuvanagiri'],
  'Tripura': ['Dhalai', 'Gomati', 'Khowai', 'North Tripura', 'Sepahijala', 'South Tripura', 'Unakoti', 'West Tripura'],
  'Uttar Pradesh': ['Agra', 'Aligarh', 'Allahabad', 'Ambedkar Nagar', 'Amethi (Chatrapati Sahuji Mahraj Nagar)', 'Amroha (J.P. Nagar)', 'Auraiya', 'Azamgarh', 'Baghpat', 'Bahraich', 'Ballia', 'Balrampur', 'Banda', 'Barabanki', 'Bareilly', 'Basti', 'Bhadohi', 'Bijnor', 'Budaun', 'Bulandshahr', 'Chandauli', 'Chitrakoot', 'Deoria', 'Etah', 'Etawah', 'Faizabad', 'Farrukhabad', 'Fatehpur', 'Firozabad', 'Gautam Buddha Nagar', 'Ghaziabad', 'Ghazipur', 'Gonda', 'Gorakhpur', 'Hamirpur', 'Hapur (Panchsheel Nagar)', 'Hardoi', 'Hathras', 'Jalaun', 'Jaunpur', 'Jhansi', 'Kannauj', 'Kanpur Dehat', 'Kanpur Nagar', 'Kanshiram Nagar (Kasganj)', 'Kaushambi', 'Kushinagar (Padrauna)', 'Lakhimpur - Kheri', 'Lalitpur', 'Lucknow', 'Maharajganj', 'Mahoba', 'Mainpuri', 'Mathura', 'Mau', 'Meerut', 'Mirzapur', 'Moradabad', 'Muzaffarnagar', 'Pilibhit', 'Pratapgarh', 'RaeBareli', 'Rampur', 'Saharanpur', 'Sambhal (Bhim Nagar)', 'Sant Kabir Nagar', 'Shahjahanpur', 'Shamali (Prabuddh Nagar)', 'Shravasti', 'Siddharth Nagar', 'Sitapur', 'Sonbhadra', 'Sultanpur', 'Unnao', 'Varanasi'],
  'Uttarakhand': ['Almora', 'Bageshwar', 'Chamoli', 'Champawat', 'Dehradun', 'Haridwar', 'Nainital', 'Pauri Garhwal', 'Pithoragarh', 'Rudraprayag', 'Tehri Garhwal', 'Udham Singh Nagar', 'Uttarkashi'],
  'West Bengal': ['Alipurduar', 'Bankura', 'Birbhum', 'Cooch Behar', 'Dakshin Dinajpur (South Dinajpur)', 'Darjeeling', 'Hooghly', 'Howrah', 'Jalpaiguri', 'Jhargram', 'Kalimpong', 'Kolkata', 'Malda', 'Murshidabad', 'Nadia', 'North 24 Parganas', 'Paschim Medinipur (West Medinipur)', 'Paschim (West) Burdwan (Bardhaman)', 'Purba Burdwan (Bardhaman)', 'Purba Medinipur (East Medinipur)', 'Purulia', 'South 24 Parganas', 'Uttar Dinajpur (North Dinajpur)'],
};
let stateList = {
  "Andhra Pradesh": 13, "Arunachal Pradesh": 26, "Assam": 34, "Bihar": 38, "Chhattisgarh": 28, "Goa": 2,
  "Gujarat": 33, "Haryana": 22, "Himachal Pradesh": 12, "Jharkhand": 24, "Karnataka": 31, "Kerala": 14, "Madhya Pradesh": 52,
  "Maharashtra": 36, "Manipur": 16, "Meghalaya": 12, "Mizoram": 8, "Nagaland": 11, "Odisha": 30, "Punjab": 23, "Rajasthan": 33,
  "Sikkim": 4, "Tamil Nadu": 38, "Telangana": 33, "Tripura": 8, "Uttar Pradesh": 75, "Uttarakhand": 13, "West Bengal": 23
};

let stateRtoCode = {
  "Andhra Pradesh": "AP", "Arunachal Pradesh": "AR", "Assam": "AS", "Bihar": "BR", "Chhattisgarh": "CG", "Goa": "GA",
  "Gujarat": "GJ", "Haryana": "HR", "Himachal Pradesh": "HP", "Jharkhand": "JH", "Karnataka": "KA", "Kerala": "KL", "Madhya Pradesh": "MP",
  "Maharashtra": "MH", "Manipur": "MN", "Meghalaya": "ML", "Mizoram": "MZ", "Nagaland": "NL", "Odisha": "OD", "Punjab": "PN", "Rajasthan": "RJ",
  "Sikkim": "SK", "Tamil Nadu": "TN", "Telangana": "TS", "Tripura": "TR", "Uttar Pradesh": "UP", "Uttarakhand": "UK", "West Bengal": "WB"
};

let stateRtoCount = {
  "Andhra Pradesh": 38, "Arunachal Pradesh": 16, "Assam": 34, "Bihar": 11, "Chhattisgarh": 30, "Goa": 6,
  "Gujarat": 38, "Haryana": 98, "Himachal Pradesh": 80, "Jharkhand": 24, "Karnataka": 71, "Kerala": 86, "Madhya Pradesh": 54,
  "Maharashtra": 50, "Manipur": 8, "Meghalaya": 14, "Mizoram": 9, "Nagaland": 8, "Odisha": 35, "Punjab": 99, "Rajasthan": 53,
  "Sikkim": 8, "Tamil Nadu": 96, "Telangana": 36, "Tripura": 8, "Uttar Pradesh": 96, "Uttarakhand": 19, "West Bengal": 78
};
let randomSentences = [
  "Improve your goldfish's physical fitness by getting him a bicycle.",
  "If you don't like toenails, you probably shouldn't look at your feet.",
  "The sudden rainstorm washed crocodiles into the ocean.",
  "Jim liked driving around town with his hazard lights on.",
  "The hawk didn’t understand why the ground squirrels didn’t want to be his friend.",
  "She felt that chill that makes the hairs on the back of your neck when he walked into the room.",
  "Courage and stupidity were all he had.",
  "The fish listened intently to what the frogs had to say.",
  "So long and thanks for the fish.",
  "It's never been my responsibility to glaze the donuts.",
  "The small white buoys marked the location of hundreds of crab pots.",
  "He decided to fake his disappearance to avoid jail.",
  "With the high wind warning",
  "The team members were hard to tell apart since they all wore their hair in a ponytail.",
  "He embraced his new life as an eggplant.",
  "The ice-cream trucks bring back bad memories for all of us.",
  "Last Friday I saw a spotted striped blue worm shake hands with a legless lizard.",
  "She thought there'd be sufficient time if she hid her watch.",
  "Nancy decided to make the porta-potty her home.",
  "I come from a tribe of head-hunters, so I will never need a shrink.",
  " Even with the snow falling outside, she felt it appropriate to wear her bikini.",
  "Their argument could be heard across the parking lot.",
  "The light that burns twice as bright burns half as long.",
  "As the asteroid hurtled toward earth, Becky was upset her dentist appointment had been canceled.",
  "He was willing to find the depths of the rabbit hole in order to be with her.",
  "Peter found road kill an excellent way to save money on dinner.",
  "The snow-covered path was no help in finding his way out of the back-country.",
  "The hand sanitizer was actually clear glue.",
  "He realized there had been several deaths on this road, but his concern rose when he saw the exact number.",
  "Her scream silenced the rowdy teenagers.",
  "He enjoys practicing his ballet in the bathroom.",
  "The teens wondered what was kept in the red shed on the far edge of the school grounds.",
  "Weather is not trivial - it's especially important when you're standing in it.",
  "She wanted a pet platypus but ended up getting a duck and a ferret instead.",
  "The most exciting eureka moment I've had was when I realized that the instructions on food packets were just guidelines.",
  "It's not possible to convince a monkey to give you a banana by promising it infinite bananas when they die.",
  "It didn't take long for Gary to detect the robbers were amateurs.",
  "She was sad to hear that fireflies are facing extinction due to artificial light, habitat loss, and pesticides.",
  "He had reached the point where he was paranoid about being paranoid.",
  "I only enjoy window shopping when the windows are transparent.",
  "Pink horses galloped across the sea.",
  "He would only survive if he kept the fire going and he could hear thunder in the distance.",
  "It didn't make sense unless you had the power to eat colors.",
  "Bill ran from the giraffe toward the dolphin.",
  "The wooden spoon couldn’t cut but left emotional scars.",
  "For some unfathomable reason, the response team didn't consider a lack of milk for my cereal as a proper emergency.",
  "Truth in advertising and dinosaurs with skateboards have much in common.",
  "The tattered work gloves speak of the many hours of hard labor he endured throughout his life.",
  "The toddler’s endless tantrum caused the entire plane anxiety.",
  "The tears of a clown make my lipstick run, but my shower cap is still intact.",
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
  "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.",
  "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  "The urgent care center was flooded with patients after the news of a new deadly virus was made public.",
  "He learned the important lesson that a picnic at the beach on a windy day is a bad idea.",
  "Alice was amazed by how quickly the sun rose over the horizon.",
  "The kids were playing hide and seek behind the curtain.",
  "The teacher asked the students to write down their favorite color using only one word each.",
  "The cat purred contentedly while watching the birds through its binoculars.",
  "The dog chased the squirrel until it got lost in the forest.",
  "The man who owned the house was known for his love of gardening.",
  "The woman who wore the pearl necklace was considered very elegant.",
  "The girl who played the flute was the star of the concert.",
  "The boy who painted the picture was very talented.",
  "The baby who slept all night without crying was a happy child.",
  "The couple who shared a bed were deeply in love.",
  "The family who traveled together always stayed connected.",
  "The person who cooked the best meal was highly appreciated.",
  "The student who studied diligently passed the examination.",
  "The athlete who trained daily became strong and healthy.",
  "The artist who created beautiful paintings was renowned worldwide.",
  "The scientist who discovered the antibiotic was hailed as a hero.",
  "The musician who composed the symphony was recognized as a genius.",
  "The writer who wrote the novel was praised for her literary skills.",
  "The chef who prepared the perfect dish was celebrated by everyone.",
  "The actor who acted in the play was admired for his acting abilities.",
  "We have never been to Asia, nor have we visited Africa.",
  "My grandmother has lived longer than anyone else I know.",
  "I don't like the taste of green beans. They remind me too much of my mother-in-law.",
  "I can't believe I forgot my glasses again!",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "What makes the sky blue? The sunsets, of course!",
  "How does a tree become a tree? It grows upwards, just like a human!",
  "Why did the elephant wear sunglasses? To protect his eyes from the bright light!",
  "Why did the cow go to the doctor? She had an 'ugly moo!'!",
  "He was sitting in a trash can with high street class.",
  "She was so hungry she could eat a horse!",
  "They are not arguing; they are just having a good conversation.",
  "When will the rain stop falling? When the sun comes out!",
  "Where does the water come from when you take a bath? From the tap!",
  "The clouds formed beautiful animals in the sky that eventually created a tornado to wreak havoc.",
  "If you want to travel far, start walking towards your dreams.",
  "You cannot judge a book by its cover. You need to read it first.",
  "Do not argue with someone who insists on being right. Instead, try to understand why they think what they say.",
  "Life is what happens when you're busy making other plans.",
  "It takes two to tango.",
  "Don’t count your chicks before they hatch.",
  "Education is the key to success.",
  "Be careful what you wish for, because you might get it.",
  "Do not let yesterday take up too much of today.",
  "Happiness is not something readymade. It must be built by your own efforts.",
  "An apple a day keeps the doctor away.",
  "Love is blind, but marriage isn't.",
  "To succeed in life, you need to work hard and stay positive.",
  "Never give up on your dreams. Keep trying even if things seem impossible.",
  "A smile is contagious. Share yours with others.",
  "Believe in yourself and you will achieve anything.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "In the end, it's not about winning or losing. It's about how you feel while playing the game.",
  "The only way to do great work is to love what you do.",
  "Your time is limited, so don’t waste it living someone else’s life.",
  "Try not to become a man of leisure; rather become a man of action.",
  "People often say that time waits for no one, but that’s not true. Patience waits for everyone.",
  "Sometimes the best thing to do is nothing at all.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The future belongs to those who prepare for it today.",
  "Life is not about waiting for the storm to pass; it’s about learning to dance in the rain.",
  "You miss 100% of the shots you don’t take.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "Remember that happiness is not something you find, it’s something you create.",
  "Every strike brings me closer to the ball.",
  "The best way to predict the future is to invent it.",
  "The whole point of going to school is to learn how to make money.",
  "The only person you should try to impress is yourself.",
  "The most difficult thing to understand is the universe itself.",
  "The only way to truly fail is to give up.",
  "There is no substitute for hard work.",
  "The only way to keep your friends is to be true to yourself.",
  "So long and thanks for the fish.",
  "She works two jobs to make ends meet; at least, that was her reason for not having time to join us.",
  "The only thing necessary for the triumph of evil is for good men to do nothing.",
  "The only thing we have to fear is fear itself.",
  "The only way to do well by means different from the best is to imitate the best.",
  "The only way to get started is to quit talking and begin doing.",
  "Time waits for nobody, especially not fools.",
  "Today is the tomorrow you worried about yesterday.",
  "Tomorrow is not so bad, after all.",
  "Trust yourself. You know more than you think you do.",
  "Two wrongs don’t make a right.",
  "Victory has a thousand fathers; defeat is an orphan.",
  "We are what we believe.",
  "When the student is ready, the teacher appears.",
  "Where there’s a will, there’s a way.",
  "Without music, life would be a error.",
  "Worry doesn’t help. All it does is make you miserable.",
  "Years may come and go, but memories last forever.",
  "You can't have everything, but you can have enough."
];
let companyNames = [
  "Noble Ventures", "Quasar Solutions", "Axis Innovations", "Nimbus Corporation",
  "Vertex Ventures", "Infinite Solutions", "Helix Corporation", "Nova Innovations",
  "Luminance Corporation", "Flare Ventures", "Zenith Solutions", "Quartz Corporation",
  "Astral Ventures", "Pulse Innovations", "Elevation Corporation", "Crest Dynamics",
  "Vortex Ventures", "Nexus Innovations", "Summit Corporation", "Eon Solutions",
  "Crest Ventures", "Noble Ventures", "Quasar Solutions", "Axis Innovations",
  "Nimbus Corporation", "Vertex Ventures", "Infinite Solutions", "Helix Corporation",
  "Nova Innovations", "Luminance Corporation", "Flare Ventures", "Zenith Solutions",
  "Quartz Corporation", "Astral Ventures", "Pulse Innovations", "Elevation Corporation",
  "Crest Dynamics", "Vortex Ventures", "Nexus Innovations", "Summit Corporation",
  "Eon Solutions", "Crest Ventures", "Noble Ventures", "Quasar Solutions",
  "Axis Innovations", "Nimbus Corporation", "Vertex Ventures", "Infinite Solutions",
  "Helix Corporation", "Nova Innovations", "Luminance Corporation", "Flare Ventures",
  "Zenith Solutions", "Quartz Corporation", "Astral Ventures", "Pulse Innovations",
  "Elevation Corporation", "Crest Dynamics", "Vortex Ventures", "Nexus Innovations",
  "Summit Corporation", "Eon Solutions", "Crest Ventures", "Noble Ventures",
  "Quasar Solutions", "Axis Innovations", "Nimbus Corporation", "Vertex Ventures",
  "Infinite Solutions", "Helix Corporation", "Nova Innovations", "Luminance Corporation",
  "Flare Ventures", "Zenith Solutions", "Quartz Corporation", "Astral Ventures",
  "Pulse Innovations", "Elevation Corporation", "Crest Dynamics", "Vortex Ventures",
  "Nexus Innovations", "Summit Corporation", "Eon Solutions", "Crest Ventures",
  "Noble Ventures", "Quasar Solutions", "Axis Innovations", "Nimbus Corporation",
  "Vertex Ventures", "Infinite Solutions", "Helix Corporation", "Nova Innovations",
  "Luminance Corporation", "Flare Ventures", "Zenith Solutions", "Quartz Corporation",
  "Astral Ventures", "Pulse Innovations", "Elevation Corporation", "Crest Dynamics",
  "Vortex Ventures", "Nexus Innovations", "Summit Corporation", "Eon Solutions",
  "Crest Ventures", "Noble Ventures", "Quasar Solutions", "Axis Innovations",
  "Nimbus Corporation", "Vertex Ventures", "Infinite Solutions", "Helix Corporation",
  "Nova Innovations", "Luminance Corporation", "Flare Ventures", "Zenith Solutions",
  "Quartz Corporation", "Astral Ventures", "Pulse Innovations", "Elevation Corporation",
  "Crest Dynamics", "Vortex Ventures", "Nexus Innovations", "Summit Corporation",
  "Eon Solutions", "Crest Ventures", "Noble Ventures", "Quasar Solutions",
  "Axis Innovations", "Nimbus Corporation", "Vertex Ventures", "Infinite Solutions",
  "Helix Corporation", "Nova Innovations", "Luminance Corporation", "Flare Ventures",
  "Zenith Solutions", "Quartz Corporation", "Astral Ventures", "Pulse Innovations",
  "Elevation Corporation", "Crest Dynamics", "Vortex Ventures", "Nexus Innovations",
  "Summit Corporation", "Eon Solutions", "Crest Ventures", "Noble Ventures",
  "Quasar Solutions", "Axis Innovations", "Nimbus Corporation", "Vertex Ventures",
  "Infinite Solutions", "Helix Corporation", "Nova Innovations", "Luminance Corporation",
  "Flare Ventures", "Zenith Solutions", "Quartz Corporation", "Astral Ventures",
  "Pulse Innovations", "Elevation Corporation", "Crest Dynamics", "Vortex Ventures",
  "Nexus Innovations", "Summit Corporation", "Eon Solutions", "Crest Ventures",
  "Noble Ventures", "Quasar Solutions", "Axis Innovations", "Nimbus Corporation",
  "Vertex Ventures", "Infinite Solutions", "Helix Corporation"
];

let typeOfBusiness = [
  "Technology company", "Financial services company", "Healthcare company", "Retail company", "Manufacturing company",
  "Construction company", "Transportation company", "Energy company", "Media company", "Entertainment company",
  "Automotive company", "Food and beverage company", "Pharmaceutical company", "Hospitality company", "Real estate company",
  "Education company", "Telecommunications company", "Consulting company", "Marketing agency", "Legal services company",
  "Insurance company", "Non-profit organization", "Environmental services company", "Travel agency", "Fashion company",
  "Agricultural company", "Biotechnology company", "Aerospace company", "Mining company", "Fitness and wellness company",
  "Software development company", "Banking institution", "Hospital", "Grocery store", "Textile manufacturer",
  "Civil engineering firm", "Logistics company", "Oil and gas company", "Broadcasting network", "Film production studio",
  "Automobile manufacturer", "Fast food chain", "Drug manufacturer", "Hotel chain", "Property management company",
  "Language school", "Internet service provider", "HR consulting firm", "Advertising agency", "Law firm",
  "Reinsurance company", "Charity organization", "Waste management company", "Tour operator", "Clothing retailer",
  "Dairy farm", "Genetic engineering company", "Satellite manufacturer", "Quarry", "Gym", "Social media platform",
  "Investment bank", "Medical clinic", "Electronics retailer", "Brewery", "University", "Mobile network operator",
  "Architecture firm", "Public relations agency", "Accounting firm", "Mutual insurance company", "Educational nonprofit",
  "Renewable energy company", "Cruise line", "Luxury fashion brand", "Dairy company", "Veterinary clinic",
  "Pharmaceutical distributor", "Web hosting company", "Event planning company", "Patent law firm", "Health insurance company",
  "Political party", "Recycling company", "Adventure travel company", "Shoe retailer", "Farm", "Environmental nonprofit",
  "Aerospace manufacturer", "Gold mining company", "Yoga studio", "Social networking site", "Retail bank",
  "Clinic", "Electronics manufacturer", "Winery", "Culinary school", "Telecom infrastructure company", "Urban planning firm",
  "Public relations firm", "Auditing firm", "Property and casualty insurance company", "Wildlife conservation organization",
  "Wind energy company", "Charter airline", "Luxury hotel", "Fashion designer", "Organic farm", "Animal shelter",
  "Food distributor", "Satellite communications company", "Investment management firm", "Dental clinic", "Computer hardware manufacturer",
  "Microbrewery", "Language translation services", "Private equity firm", "Medical equipment manufacturer", "Coffee shop",
  "Maritime shipping company", "Independent film studio", "Bakery", "Culinary institute", "Fiber optic cable manufacturer",
  "Internet marketing agency", "Patent consulting firm", "Travel insurance company", "Advocacy group", "Solar energy company",
  "Luxury cruise line", "Luxury fashion retailer", "Cheese manufacturer", "Veterinary hospital", "Biomedical research company",
  "Cloud computing provider", "Event management company", "Intellectual property law firm", "Health club", "Social media marketing agency",
  "Investment advisory firm", "Plastic recycling company", "Eco-tourism company", "Sneaker retailer", "Dairy processing plant",
  "Wildlife rehabilitation center", "Aerospace engineering firm", "Silver mining company", "Pilates studio", "Dating website",
  "Community bank", "Dermatology clinic", "Video game developer", "Bicycle manufacturer", "Film distribution company",
  "Cooking school", "Telecom equipment manufacturer", "Boutique hotel", "Fashion boutique", "Organic food store",
  "Nonprofit foundation", "Cable television provider", "Public policy think tank", "Wind turbine manufacturer", "Private jet charter company",
  "Luxury resort", "Wedding planning company", "Intellectual property consulting firm", "Fitness equipment manufacturer",
  "Social justice organization", "Urban farming company", "Luxury car manufacturer", "Film production company", "Gourmet restaurant",
  "Maritime logistics company", "Independent bookstore", "Animation studio", "Craft brewery", "Language tutoring center",
  "Venture capital firm", "Medical research laboratory", "Tea company", "Mountain resort", "Bioinformatics company",
  "Satellite imagery provider", "Personal finance blog", "Wildlife sanctuary", "Space tourism company", "Fashion magazine",
  "Organic skincare brand", "Public library", "Online marketplace", "Nonprofit theater company", "Sustainable energy consultancy",
  "Artisanal chocolatier", "Software consultancy", "Mobile app development company", "Health food store", "Environmental law firm",
  "Yoga retreat center", "Social impact investment fund", "Research and development lab", "Luxury spa", "Music production studio",
  "Ethical clothing brand", "Food truck", "E-commerce platform", "Community theater", "Sustainable agriculture company",
  "Biodiversity conservation organization", "Satellite launch provider", "Interior design firm", "Private tutoring service",
  "Angel investment group", "Medical billing company", "Tea shop", "Ski resort", "Digital marketing agency", "Ethical investment firm",
  "Green energy provider", "Botanical garden", "Renewable energy consultancy", "Luxury safari company", "Gourmet food store",
  "Art gallery", "Software security company", "Mobile phone manufacturer", "Meditation retreat center", "Human rights organization",
  "Sustainable fashion brand", "Travel booking website", "Personal training studio", "Social entrepreneurship incubator",
  "Nutritionist consultancy", "Cultural center", "Sustainable architecture firm", "Music streaming service", "Wildlife photography tour operator",
  "Vegan restaurant", "Environmental consulting firm", "Artisanal bakery", "Financial literacy nonprofit", "Eco-friendly cleaning product company",
  "Video game publisher", "Mountain guiding service", "Fair trade coffee roaster", "Renewable energy investment fund", "Environmental education center",
  "Sustainable tourism operator", "Performing arts center", "Financial planning firm", "Social enterprise accelerator", "Sustainable transportation company",
  "Ethical jewelry brand", "Organic juice bar", "Vegan clothing store", "Software testing company", "Mobile payment provider",
  "Meditation app developer", "Animal rights advocacy group", "Renewable energy technology startup", "Eco-conscious fashion boutique",
  "Carbon offsetting company", "Natural skincare brand", "Eco-friendly furniture manufacturer", "Clean energy investment firm",
  "Organic gardening store", "Sustainable seafood restaurant", "Renewable energy consulting firm", "Fair trade fashion label",
  "Ethical investment bank", "Wildlife conservation charity", "Vegan cosmetics company", "Environmental research institute",
  "Artisanal soap maker", "Sustainable energy startup", "Green building consultancy", "Animal welfare organization", "Ethical travel agency",
  "Organic baby clothing store", "Renewable energy infrastructure developer", "Eco-friendly cleaning service"
];
let gstCodeArray = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
  "21", "22", "23", "24", "26", "27", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "97", "99"]

let domainExtensionsArray = ['.com', '.net', '.org', '.io', '.gov', '.edu', '.biz', '.info', '.co', '.tv', '.me', '.us', '.uk', '.ca', '.au', '.de', '.fr',
  '.jp', '.cn', '.in', '.ru', '.nl', '.it', '.br', '.mx', '.es', '.ch', '.se', '.no', '.fi', '.dk', '.pl', '.cz', '.gr', '.hu', '.at', '.be',
  '.pt', '.nz', '.sa', '.ae', '.qa', '.tw', '.kr', '.hk', '.sg', '.my', '.id', '.th', '.vn', '.ph', '.cl', '.ar', '.co.uk', '.co.jp', '.co.kr',
  '.co.in', '.co.id', '.co.za', '.co.nz', '.co.il', '.co.th', '.co.at', '.co.hu', '.co.za', '.co.nz', '.co.il', '.co.th', '.co.at', '.co.hu', '.co.za', '.co.nz', '.co.il', '.co.th', '.co.at', '.co.hu', '.co.za', '.co.nz', '.co.il', '.co.th', '.co.at', '.co.hu', '.co.za', '.co.nz', '.co.il', '.co.th', '.co.at', '.co.hu', '.co.za', '.co.nz', '.co.il', '.co.th', '.co.at', '.co.hu'];

module.exports = {
  firstMaleName, title, emlDomain, upiDomain, gender, hairColor, skinColor, bloodGroup, eyeColor,
  stateName, stateDist, stateList, stateRtoCode, stateRtoCount, randomSentences, typeOfBusiness, companyNames, gstCodeArray, domainExtensionsArray
};