import userData from '../../pirated-data/package/copyed.js';
// const userData = require('pirated-data');
// var result = userData.add(4,5)
// console.log(result);
var startname = userData.firstNameGenerator();
console.log("First name: "+startname);
var lastName =userData.lastNameGenerator();
console.log("Last name: "+lastName);
var fulName = userData.fullNameGenerator();
console.log(fulName);
var age = userData.adultAgeGenerator();
console.log("Age: "+age);
var mobnum = userData.mobileNumberGenerator();
console.log("Mobile number of user: "+mobnum);
var aadhar = userData.aadharNumberGenerator();
console.log("Aaadhar number: "+aadhar);
var eml = userData.emailIdGenerator();
console.log("Email id: "+eml);
var usrId = userData.userIdGenerator();
console.log("Userid of user: "+usrId);
var pwd = userData.passwordGenerator(10);
console.log("Password of the user: "+pwd);
var gender = userData.genderGenerator();
console.log("Gender of the user:"+gender);
var hrclr = userData.hairColorGenerator();
console.log("user hair color is: "+hrclr);
var eyeclr = userData.eyeColorGenerator();
console.log("eye color of a user is: ", eyeclr);
var bldgrp  = userData.bloodGroupGenerator();
console.log("blood group is: ",bldgrp);
var wt = userData.weightGenerator();
console.log("weight of a user is: ",wt)
var biology = userData.BiologicalData();
console.log(biology);
// var bnkName = userData.bankNameGenerator();
// console.log("Bank name of user: "+bnkName);
var state = userData.stateGenerator();
console.log("State name is: "+state);
var dist = userData.distGenerator();
console.log(dist);
var address = userData.addressGenerator();
console.log(address);
var card = userData.financialCardGenerator();
console.log("Card number: "+card);
// var bkfstnme = userData.breakastGenerator();
// console.log(bkfstnme);
// var lnchcrynme = userData.lunchCurryGenerator();
// console.log(lnchcrynme);
 var bnchAddress = userData.hugeAddressGenerator(50);
console.log(bnchAddress);

var bnchBio = userData.hugeBiologicalDataGenerator(10);
console.log(bnchBio);
var id = userData.panCardId();
console.log(id);
// const d = userData.birthDateTimeGenerator( );
// console.log(d);
// const age = userData.ageCalculation();
// console.log(age);

// console.log(add);
